USB_VID = 0x0483
USB_PID = 0x5740
USB_PRODUCT = "Daisy Seed"
USB_MANUFACTURER = "STMicroelectronics"

# INTERNAL_FLASH_FILESYSTEM = 1
QSPI_FLASH_FILESYSTEM = 1
# EXTERNAL_FLASH_DEVICES = N25Q128A

MCU_SERIES = H7
MCU_VARIANT = STM32H750xx
MCU_PACKAGE = UFBGA176

LD_COMMON = boards/common_tcm.ld
LD_FILE = boards/STM32H750.ld
